<? /*
    J S C R I P T  +  V A R S
*/ ?>

<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
$this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
$this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
'<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();

$this->layout()->ignoreHiddenFiltersInRequest = true;
$this->layout()->ignoreHiddenFilterMemory = true;
?>

<div class="fullrecord_view">
  <div class="row">
    <div class="col-sm-7 cols-xs-12">
    <? /*
        S C R O L L D A T A
    */ ?>
    <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
      <ul class="pager hidden-print pull-right" style="margin-bottom:0px;">

        <? if ($this->scrollData['previousRecord']): ?>
        <? if ($this->scrollData['firstRecord']): ?>
        <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['firstRecord']) ?>" title="<?= $this->transEsc('First Search Result') ?>" rel="nofollow">&laquo; <?= $this->transEsc('First') ?></a>
        </li>
        <? endif; ?>
        <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>" title="<?= $this->transEsc('Previous Search Result') ?>" rel="nofollow">&laquo;</a>
        </li>
        <? else: ?>
        <? if ($this->scrollData['firstRecord']): ?>
        <li class="disabled"><a href="#">&laquo;</a></li>
        <? endif; ?>
        <li class="disabled"><a href="#">&laquo;</a></li>
        <? endif; ?>
        <?=$this->transEsc('of_num_results', [
                                '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
                                '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
                            ]) ?>
        <? if ($this->scrollData['nextRecord']): ?>
        <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>" title="<?= $this->transEsc('Next Search Result') ?>" rel="nofollow">&raquo;</a>
        </li>
        <? if ($this->scrollData['lastRecord']): ?>
        <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['lastRecord']) ?>" title="<?= $this->transEsc('Last Search Result') ?>" rel="nofollow"><?= $this->transEsc('Last') ?> &raquo;</a>
        </li>
        <? endif; ?>
        <? else: ?>
        <li class="disabled"><a href="#">&raquo;</a></li>
        <? if ($this->scrollData['lastRecord']): ?>
        <li class="disabled"><a href="#"><?= $this->transEsc('Last') ?> &raquo;</a></li>
        <? endif; ?>
        <? endif; ?>
      </ul>
    <? endif; ?>
    </div>
    <div class="col-sm-5 col-xs-12">
      <? /*
          T O O L B A R
      */ ?>
      <?= $this->record($this->driver)->getToolbar() ?>
    </div>
  </div>

  <? /*
      F U L L R E C O R D V I E W
  */ ?>
  <div class="record source<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>">
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId" />
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
    <?= $this->flashmessages() ?>
    <?= $this->record($this->driver)->getCoreMetadata() ?>


  <? /*
      T A B S
  */ ?>
    <? if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <div class="record-tabs">
        <ul class="nav nav-tabs">
            <? foreach ($this->tabs as $tab => $obj): ?>
            <? // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $tab_classes = [];
            if (0 === strcasecmp($this->activeTab, $tab)) {
            if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
            $tab_classes[] = 'active';
            }
            $tab_classes[] = 'initiallyActive';
            $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
            $activeTabObj = $obj;
            }
            if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
            if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
            ?>
            <li<?= count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : '' ?>>
                <a class="<?= strtolower($tab) ?>" href="<?= $this->recordLink()->getTabUrl($this->driver, $tab) ?>#tabnav"<? if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<? endif ?>><?= $this->transEsc($desc) ?></a>
            </li>
            <? endforeach; ?>
        </ul>

        <div class="tab-content">
            <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?= $this->activeTab ?>-tab">
                <?= isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
            <? endif; ?>
        </div>
    </div>
    <? endif; ?>

    <?= $this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : '' ?>
  </div>
<?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
</div>