<?php /*
    J S C R I P T  +  V A R S
*/ ?>

<?php
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()
              ->getLastSearchLink('<span>' . $this->transEsc('Search results') . '</span>', '<li>', '</li>');
  $this->layout()->title = $this->driver->getShortTitle();

  $this->layout()->ignoreHiddenFiltersInRequest = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>

<div class="fullrecord_view">
  <div class="row">
    <div class="col-sm-7 cols-xs-12">
    <?php /*
        S C R O L L D A T A
    */ ?>
    <?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
      <ul class="pager hidden-print pull-right" style="margin-bottom:0;">
        <?php if ($this->scrollData['previousRecord']): ?>
          <?php if ($this->scrollData['firstRecord']): ?>
            <li>
              <a href="<?= $this->recordLink()->getUrl($this->scrollData['firstRecord']) ?>" title="<?= $this->transEscAttr('First Search Result') ?>" rel="nofollow">&laquo; <?= $this->transEsc('First') ?></a>
            </li>
          <?php endif; ?>
          <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['previousRecord']) ?>" title="<?= $this->transEscAttr('Previous Search Result') ?>" rel="nofollow">&laquo;</a>
          </li>
        <?php else: ?>
          <?php if ($this->scrollData['firstRecord']): ?>
            <li class="disabled"><a href="#">&laquo;</a></li>
          <?php endif; ?>
          <li class="disabled"><a href="#">&laquo;</a></li>
        <?php endif; ?>
        <?= $this->transEsc('of_num_results', [
          '%%position%%' => $this->localizedNumber($this->scrollData['currentPosition']),
          '%%total%%' => $this->localizedNumber($this->scrollData['resultTotal'])
        ]) ?>
        <?php if ($this->scrollData['nextRecord']): ?>
          <li>
            <a href="<?= $this->recordLink()->getUrl($this->scrollData['nextRecord']) ?>" title="<?= $this->transEscAttr('Next Search Result') ?>" rel="nofollow">&raquo;</a>
          </li>
          <?php if ($this->scrollData['lastRecord']): ?>
            <li>
              <a href="<?= $this->recordLink()->getUrl($this->scrollData['lastRecord']) ?>" title="<?= $this->transEscAttr('Last Search Result') ?>" rel="nofollow"><?= $this->transEsc('Last') ?> &raquo;</a>
            </li>
          <?php endif; ?>
        <?php else: ?>
          <li class="disabled"><a href="#">&raquo;</a></li>
          <?php if ($this->scrollData['lastRecord']): ?>
            <li class="disabled"><a href="#"><?= $this->transEsc('Last') ?> &raquo;</a></li>
          <?php endif; ?>
        <?php endif; ?>
      </ul>
    <?php endif; ?>
    </div>
    <div class="col-sm-5 col-xs-12">
      <?php /*
          T O O L B A R
      */ ?>
      <?= $this->record($this->driver)->getToolbar() ?>
    </div>
  </div>

  <?php /*
      F U L L R E C O R D V I E W
  */ ?>
  <div class="record source<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>">
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId" />
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
    <?= $this->flashmessages() ?>
    <?= $this->record($this->driver)->getCoreMetadata() ?>

    <?php /*
        T A B S
    */ ?>
    <?php if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <div class="record-tabs">
      <ul class="nav nav-tabs">
        <?php foreach ($this->tabs as $tab => $obj): ?>
          <?php // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $tab_classes = [];
            $tabName = preg_replace("/\W/", "-", strtolower($tab));
            if (0 === strcasecmp($this->activeTab, $tab)) {
              if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                $tab_classes[] = 'active';
              }
              $tab_classes[] = 'initiallyActive';
              $activeTabObj = $obj;
            }
            if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
            if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
          ?>
          <li class="<?= implode(' ', $tab_classes)?>" data-tab="<?= $tabName?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
            <a href="<?= $this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?= $this->transEsc($desc)?></a>
          </li>
        <?php endforeach; ?>
      </ul>

      <div class="tab-content">
        <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
          <div class="tab-pane active <?= $this->escapeHtmlAttr($this->activeTab) ?>-tab">
            <?= isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
    <?php endif; ?>

    <?= $this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : '' ?>
  </div>
  <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
</div>