<?php
    $citesCount = is_callable([$this->driver, 'getCitatedReferencesCount']) ? $this->driver->getCitatedReferencesCount() : false;
    $citesLink = is_callable([$this->driver, 'getCitatedReferencesLink']) ? $this->driver->getCitatedReferencesLink() : false;
?>
<?php if ($citesCount) :?>
<span class="speech-bubble html-tooltip" title="<?= $this->translate('Web of Science Scites Tooltip')?>"><?php if ($citesLink):?><a href="<?= $citesLink?>" target="_blank"><?= $citesCount?></a><?php else: ?><?= $citesCount?><?php endif; ?></span>
<?php endif;?>
