<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?= $this->driver->getSchemaOrgFormats()?> Product">
  <?php $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews();
     $this->jsTranslations()->addStrings(array('truncate_more' => 'truncate_more', 'truncate_less' => 'truncate_less'));
     $this->jsTranslations()->addStrings(
         [
             'noHoldings' => 'see volumes tab for further holdings'
         ]
     );
  ?>
  

<?php /*
    P I C
*/ ?>

  <?php if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-2 img-col" style="margin-top:20px;">
    <div class="text-center">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?= $cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?= $this->transEsc('QR Code')?>" class="qrcode" src="<?= $this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>
    </div>

    <?php // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?php if ($preview): ?><?= $preview?><?php endif; ?>
  </div>


<?php /*
    C O R E M E T A D A T A
*/ ?>

  <div class="col-sm-10 info-col">
  <?php else: ?>
  <div class="col-sm-12">
  <?php endif; ?>

    <?= $this->record($this->driver)->renderTemplate('core-titleHeadline.phtml')?>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p class="truncate"><?= $summary?></p>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?= $this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */?>
    <?php
      $formatter = $this->recordDataFormatter();
      $metadataFields = $formatter->getData($driver, $formatter->getDefaults('full'));
    ?>
    <?php if (!empty($metadataFields)): ?>
      <table class="table table-responsive" summary="<?= $this->transEsc('Bibliographic Details')?>">
          <colgroup>
            <col class="col-xs-4 col-sm-3 col-md-3">
            <col class="col-xs-8 col-sm-9 col-md-10">
        </colgroup>
        <?php foreach ($metadataFields as $current): ?>
          <tr><th><?= $this->transEsc($current['label'])?>:</th><td><?= $current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */?>
  </div>
</div>
