<?php
    $lines = [];
    foreach ($data as $recordLink) {
      $singleLine = $this->transEsc($recordLink['title']) . ': ';
      if(isset($recordLink['link'])) {
          $singleLine .= '<a href="/Record/' . $recordLink['link']['value'] . '">' .
              $this->escapeHtml($recordLink['value']) . '</a>';
      }
      else {
        $singleLine .= $this->escapeHtml($recordLink['value']);
      }
      $singleLine = ($recordLink['pages']) ? $singleLine . ' ' . $recordLink['pages'] : $singleLine;
      $lines[] = $singleLine;
    }
?>
<?= implode('<br />', $lines)?>
<?php /* if we have record links, display relevant explanatory notes */
  $related = $this->driver->getRelationshipNotes();
  if (!empty($related)): ?>
    <?php foreach ($related as $field): ?>
      <?= $this->escapeHtml($field)?><br/>
    <?php endforeach; ?>
<?php endif; ?>
