<?php $classification = $this->driver->tryMethod('getBasicClassification'); ?>
<?php $i = 0; ?>
<?php if ($classification): ?>
  <?php foreach ($classification as $class): ?>
    <?= ($i++ > 0) ? '<br />' : '' ?>
    <a href="<?= $this->url('search-results')?>?lookfor=%22<?= urlencode($class['bklnumber'])?>%22&amp;type=bklnumber">
      <?= $class['bklnumber'] . ' ' . (is_array($class['bklname']) ? implode(', ', $class['bklname']) : ''); ?>
    </a>
  <?php endforeach; ?>
<?php endif; ?>