<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getSourceIdentifier();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  $editable = $this->user && $user_id === $this->user->id;

  // Thumbnail
  $coverDetails = $this->record($this->driver)->getCoverDetails('list-entry', 'medium', $this->recordLink()->getUrl($this->driver));
  $cover = $coverDetails['html'];
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('list');
  if ($cover):
    ob_start(); ?>
    <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
      <?=$cover ?>
    </div>
    <? $thumbnail = ob_get_contents(); ?>
  <? ob_end_clean(); ?>
<? endif; ?>
<div class="result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($id) ?>" class="hiddenId"/>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($source) ?>" class="hiddenSource"/>
  <div class="checkbox hidden-print">
    <label><?=$this->record($this->driver)->getCheckbox()?></label>
  </div>
  <div class="media">
    <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
      <?=$thumbnail ?>
    <? endif; ?>
    <div class="media-body">
      <div class="row short-view">
        <div class="col-sm-<?=$editable ? '10' : '12'?>">
          <div class="resultItemLine1">
            <? $missing = $this->driver instanceof \VuFind\RecordDriver\Missing; ?>
            <? if (!$missing): ?><a href="<?=$this->recordLink()->getUrl($this->driver)?>" class="getFull title truncate" data-view="<?=$this->params->getOptions()->getListViewOption() ?>"><? endif; ?>
              <?=$this->record($this->driver)->getTitleHtml()?>
            <? if (!$missing): ?></a><? endif; ?>
          </div>

          <div class="resultItemLine2">
            <?=$this->record($this->driver)->renderTemplate('result-list-publicationDetails.phtml')?>
          </div>

          <div class="last">
            <? if(!$this->driver->isCollection()) {
                if ($snippet = $this->driver->getHighlightedSnippet()) {
                  if (!empty($snippet['caption'])) {
                    echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
                  }
                  if (!empty($snippet['snippet'])) {
                    echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
                  }
                }
              } ?>

            <div class="callnumAndLocation ajax-availability hidden">
                <?php if ($this->driver->supportsAjaxStatus()): ?>
                  <strong class="hideIfDetailed"><?=$this->transEsc('Call Number')?>:</strong>
                  <span class="callnumber ajax-availability hidden">
                  <?=$this->transEsc('Loading')?>...<br/>
                </span>
                  <strong><?=$this->transEsc('Location_s')?>:</strong>
                  <span class="location ajax-availability hidden">
                  <?=$this->transEsc('Loading')?>...
                </span>
                  <div class="locationDetails"></div>
                <?php else: ?>
                    <?php $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
                    <strong class=""><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <? $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
                null === $list_id ? true : $list_id, // get tags for all lists if no single list is selected
                $user_id, 'tag'
               ) : array();
            ?>
            <? if (count($listTags) > 0): ?>
              <strong><?=$this->transEsc('Your Tags')?>:</strong>
              <? foreach ($listTags as $tag): ?>
                <a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a>
              <? endforeach; ?>
              <br/>
            <? endif; ?>
            <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
            <? if (count($listNotes) > 0): ?>
              <strong><?=$this->transEsc('Notes')?>:</strong>
              <? if (count($listNotes) > 1): ?><br/><? endif; ?>
              <? foreach ($listNotes as $note): ?>
                <?=$this->escapeHtml($note)?><br/>
              <? endforeach; ?>
            <? endif; ?>

            <? if (count($this->lists) > 0): ?>
                <strong><?=$this->transEsc('Saved in')?>:</strong>
                <? $i=0;foreach($this->lists as $current): ?>
                    <a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$this->escapeHtml($current->title)?></a><? if($i++ < count($this->lists)-1): ?>,<? endif; ?>
                <? endforeach; ?>
                <br/>
            <? endif; ?>

            <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
                  but even if we don't plan to display the link, we still want to get the $openUrl
                  value for use in generating a COinS (Z3988) tag -- see bottom of file.
                */
              $openUrl = $this->openUrl($this->driver, 'results');
              $openUrlActive = $openUrl->isActive();
              // Account for replace_other_urls setting
              $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);

              if ($openUrlActive || !empty($urls)):
            ?>
              <? if ($openUrlActive): ?>
                <br/>
                <?=$openUrl->renderTemplate()?>
              <? endif;?>

              <? if (!is_array($urls)) { $urls = array(); }
                if(!$this->driver->isCollection()):
                  foreach ($urls as $current): ?>
                    <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link" aria-hidden="true"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a>
                  <? endforeach; ?>
                  <br/>
                <? endif; ?>
              <? endif; ?>

            <?=$this->record($this->driver)->getFormatList() ?>

            <? if (!$openUrlActive && $this->driver->supportsAjaxStatus()): ?>
              <span class="status ajax-availability hidden"><?=$this->transEsc('Loading')?>...</span>
              <br/>
            <? endif; ?>
            <?=$this->record($this->driver)->getPreviews()?>
          </div>
        </div>

        <? if ($editable) : ?>
          <div class="col-sm-2 right">
            <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><i class="fa fa-fw fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Edit')?></a><br/>
            <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
              $deleteUrl = null === $list_id
                  ? $this->url('myresearch-favorites')
                  : $this->url('userList', array('id' => $list_id));
              $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);

              $dLabel = 'delete-label-' . preg_replace('[\W]','-',$id);
            ?>
            <div class="dropdown">
              <a class="dropdown-toggle" id="<?=$dLabel ?>" role="button" data-toggle="dropdown" href="<?=$deleteUrlGet ?>">
                <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> <?=$this->transEsc('Delete') ?>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="<?=$dLabel ?>">
                <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeJs($id) ?>','source':'<?=$this->escapeJs($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
                <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
              </ul>
            </div>

            <?=$this->driver->supportsCoinsOpenUrl()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenUrl()).'"></span>':''?>
          </div>
        <? endif; ?>
      </div>
    </div>
    <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
      <?=$thumbnail ?>
    <? endif; ?>
  </div>
</div>
