<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?= $this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?= $this->escapeHtmlAttr($list->title)?>" />
<?php endif; ?>
<?php $user = $this->auth()->isLoggedIn(); ?>

<div class="cart-controls flex-center clearfix hidden-print">
  <div class="checkbox pull-left flip">
    <label class="flex">
      <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
      <span><?= $this->transEsc('select_page')?></span>
    </label>
  </div>

  <div class="btn-group pull-left flip">
    <button class="btn btn-thulb" type="submit" name="email" value="<?= $this->transEsc('Email')?>" title="<?= $this->transEsc('email_selected')?>"><i class="fa fa-envelope" aria-hidden="true"></i></button>
    <?php if ((!is_null($this->list) && $this->list->editAllowed($user)) || is_null($this->list) && $user): ?>
      <button class="btn btn-thulb" id="<?= $this->idPrefix?>delete_list_items_<?= !is_null($this->list) ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?= $this->transEsc('Delete')?>" title="<?= $this->transEsc('delete_selected')?>"><i class="fa fa-trash" aria-hidden="true"></i></button>
    <?php endif; ?>
    <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
      <button class="btn btn-thulb" type="submit" name="export" value="<?= $this->transEsc('Export')?>" title="<?= $this->transEsc('export_selected')?>"><i class="fa fa-share" aria-hidden="true"></i></button>
    <?php endif; ?>
    <!--<button class="btn btn-thulb" type="submit" name="print" value="<?= $this->transEsc('Print')?>" title="<?= $this->transEsc('print_selected')?>" data-lightbox-ignore><i class="fa fa-printer" aria-hidden="true"></i></button>-->
    <?php if ($this->cart()->isActive()): ?>
      <button class="btn btn-thulb" id="<?= $this->idPrefix?>updateCart" type="submit" name="add" name="bookbag" title="<?= $this->transEsc('Add to Book Bag')?>"><i class="fa fa-plus-square" aria-hidden="true"></i></button>
    <?php endif; ?>
  </div>
</div>