<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?= $this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?= $this->escapeHtmlAttr($list->title)?>" />
<?php endif; ?>
<?php $user = $this->auth()->isLoggedIn(); ?>

<div class="cart-controls flex-center hidden-print">
  <div class="checkbox pull-left flip">
    <label class="flex-center center-text">
      <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
      <span><?= $this->transEsc('select_page')?></span>
    </label>
  </div>

  <div class="item-count">
    <?php $recordTotal = $this->results->getResultTotal(); ?>
    <?php if ($recordTotal > 0): ?>
      <?php
        $transParams = [
          '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
          '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
          '%%total%%' => $this->localizedNumber($recordTotal)
        ];
      ?>
      <?= $this->translate('showing_items_of_html', $transParams); ?>
    <?php endif; ?>
  </div>

  <div class="btn-group pull-left flip">
    <button class="btn btn-thulb" type="submit" name="email" value="<?= $this->transEscAttr('Email')?>" title="<?= $this->transEscAttr('email_selected')?>"><i class="fa fa-envelope" aria-hidden="true"></i></button>
    <?php if ((!is_null($this->list) && $this->list->editAllowed($user)) || is_null($this->list) && $user): ?>
      <button class="btn btn-thulb" id="<?= $this->idPrefix?>delete_list_items_<?= !is_null($this->list) ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?= $this->transEscAttr('Delete')?>" title="<?= $this->transEscAttr('delete_selected')?>"><i class="fa fa-trash" aria-hidden="true"></i></button>
    <?php endif; ?>
    <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
      <button class="btn btn-thulb" type="submit" name="export" value="<?= $this->transEscAttr('Export')?>" title="<?= $this->transEscAttr('export_selected')?>"><i class="fa fa-share" aria-hidden="true"></i></button>
    <?php endif; ?>
    <!--<button class="btn btn-thulb" type="submit" name="print" value="<?= $this->transEscAttr('Print')?>" title="<?= $this->transEscAttr('print_selected')?>" data-lightbox-ignore><i class="fa fa-printer" aria-hidden="true"></i></button>-->
    <?php if ($this->cart()->isActive()): ?>
      <button class="btn btn-thulb" id="<?= $this->idPrefix?>updateCart" type="submit" name="add" name="bookbag" title="<?= $this->transEscAttr('Add to Book Bag')?>"><i class="fa fa-plus-square" aria-hidden="true"></i></button>
    <?php endif; ?>
  </div>
</div>