<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <? if (!empty($this->transactions)): ?>
      <? if ($this->renewForm): ?>
      <form name="renewals" method="post" id="renewals">
        <div class="toolbar">
          <div class="checkbox">
            <label>
              <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
              <?=$this->transEsc('select_page')?> |
            </label>
            <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
            <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
          </div>
        </div>
      <? endif; ?>

      <? if ($paginator): ?>
        <?
          $end = min(
            $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
            $paginator->getTotalItemCount()
          );
          $transParams = [
            '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
            '%%end%%'   => $this->localizedNumber($end),
            '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount()),
            '%%subject%%' => $this->transEsc('Your Checked Out Items'),
          ];
        ?>
        <?=$this->translate('showing_items_of_for_html', $transParams); ?>
      <? endif; ?>

      <? foreach ($hiddenTransactions as $ilsDetails): ?>
        <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
          <? $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
          <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
          <? else: ?>
            <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
          <? endif; ?>
        <? endif; ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <? endif; ?>
      <? endforeach; ?>

      <? $i = 0; foreach ($this->transactions as $resource): ?>
        <hr/>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
          <? if ($this->renewForm): ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
                <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              </div>
            <? else: ?>
              <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" disabled="disabled" />
              </div>
            <? endif; ?>
          <? endif; ?>
          
          <div class="col-xs-11">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $this->record($resource)->getTitleHtml();
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title truncate">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
                echo '<br />';
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
                echo '<br />';
              }
            ?>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['callnumber'])) : ?>
              <strong><?=$this->transEsc('sort_callnumber')?>:</strong> <?=$this->escapeHtml($ilsDetails['callnumber'])?>
              <br />
            <? endif; ?>
            
            <? if (isset($ilsDetails['renew']) && $ilsDetails['renew'] > 0): ?>
              <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
              <? if (isset($ilsDetails['renewLimit'])): ?>
                / <?=$this->transEsc($ilsDetails['renewLimit'])?>
              <? endif; ?>
              <br />
            <? endif; ?>
            
            <? if (isset($ilsDetails['reminder']) && $ilsDetails['reminder'] > 0): ?>
              <strong><?=$this->transEsc('Reminder')?>:</strong> <?=$this->transEsc($ilsDetails['reminder'])?>
              <br />
            <? endif; ?>

            <? $showStatus = true; ?>

            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <? $showStatus = false; ?>
                <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?></strong> <? if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><? endif; ?>
                <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div><br />
              <? else: ?>
                <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?></strong><?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
                <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div><br />
              <? endif; ?>
            <? else: ?>
              <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?></strong><?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
              <? if ($showStatus): ?>
                <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                  <div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                  <div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
                <? endif; ?>
                <br />
              <? endif; ?>
            <? endif; ?>
            
            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($this->pickup): ?>
                <? foreach ($this->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEscWithPrefix('location_', $pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br />
            <? endif; ?>
            
            <?if (!isset($ilsDetails['renewable']) || !$ilsDetails['renewable']) : ?>
                <? if (isset($ilsDetails['reminder']) && $ilsDetails['reminder'] > 2): ?>
                  <span class="text-danger"><?=$this->transEsc('Online deactivated because of reminders')?></span>
                  <br />
                <? elseif (isset($ilsDetails['queue']) && $ilsDetails['queue'] > 0): ?>
                  <span class="text-danger"><?=$this->transEsc('No renewal bacause of reservations')?></span>
                  <br />
                <? elseif (isset($ilsDetails['renew']) && $ilsDetails['renew'] > 2): ?>
                  <span class="text-danger"><?=$this->transEsc('Maximum number of renewals reached')?></span>
                  <br />
                <? else: ?>
                  <span class="text-danger"><?=$this->transEsc('Renewal not possible')?></span>
                  <br />
                <? endif; ?>
            <? endif; ?>

            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <? endif; ?>
          </div>
        </div>
      <? endforeach; ?>
      <hr/>
      <? if ($this->renewForm): ?></form><? endif; ?>
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    <? else: ?>
      <?=$this->transEsc('You do not have any items checked out')?>.
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
  </div>
</div>
