<?php
    // Set up page title:
    $this->headTitle($this->translate('Change Password'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Change Password') . '</li>';
?>
<?php if ($this->auth()->isLoggedIn()): ?>
  <div class="row">
    <div class="<?= $this->layoutClass('mainbody')?>">
<?php endif; ?>

<h2><?= $this->transEsc('Change Password') ?></h2>
<?= $this->flashmessages() ?>

<p>
    <?= $this->transEsc('ils_pwd_change_intro')?>
</p>
<p>
    <?= $this->translate('ils_pwd_change_reference');?>
</p>

<?php if ($this->auth()->isLoggedIn()): ?>
    </div>
    <div class="<?= $this->layoutClass('sidebar')?>">
      <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'newpasswordlink'])?>
    </div>
  </div>
<?php endif; ?>
