<?
    // Set up page title:
    $this->headTitle($this->translate('Create New Password'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Create New Password') . '</li>';
?>
<? if ($this->auth()->isLoggedIn()): ?>
  <div class="row">
    <div class="<?=$this->layoutClass('mainbody')?>">
<? endif; ?>

<h2><?=$this->transEsc('Create New Password') ?></h2>
<?=$this->flashmessages() ?>

<p>
    <?=$this->transEsc('ils_pwd_change_intro')?>
</p>
<p>
    <?= sprintf($this->translate('ils_pwd_change_goto'), $this->userId);?>
</p>

<? if ($this->auth()->isLoggedIn()): ?>
    </div>
    <div class="<?=$this->layoutClass('sidebar')?>">
      <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'newpasswordlink'])?>
    </div>
  </div>
<? endif; ?>
