<h4><?=$this->transEsc('Your Account')?></h4>
<div class="myresearch-menu">
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <? if ($this->ils()->checkCapability('getMyTransactions')): ?>
      <a href="<?=$this->url('myresearch-checkedout')?>" class="<?=$this->active == 'checkedout' ? ' active' : ''?>">
        <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('Checked Out Items')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyProvidedItems')): ?>
      <a href="<?=$this->url('default', ['controller' => 'my-research', 'action' => 'provided'])?>" class="<?=$this->active == 'provided' ? ' active' : ''?>">
        <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('Provided Items')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyHoldsAndSRR')): ?>
      <a href="<?=$this->url('default', ['controller' => 'my-research', 'action' => 'holdsandsrr'])?>" class="<?=$this->active == 'holdsandsrr' ? ' active' : ''?>">
        <i class="fa fa-fw fa-flag" aria-hidden="true"></i> <?=$this->transEsc('Holds and Recalls')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests')): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?>
    </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyFines')): ?>
      <a href="<?=$this->url('myresearch-fines')?>" class="<?=$this->active == 'fines' ? ' active' : ''?>">
        <i class="fa fa-fw fa-eur" aria-hidden="true"></i> <?=$this->transEsc('Fines')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyProfile')): ?>
      <a href="<?=$this->url('myresearch-profile')?>" class="<?=$this->active == 'profile' ? ' active' : ''?>">
        <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
      </a>
    <? endif; ?>
    <? $user = $this->auth()->isLoggedIn(); if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>" class="<?=$this->active == 'librarycards' ? ' active' : ''?>">
        <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
      </a>
    <? endif; ?>
  <? endif; ?>
  <? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
    <div class="myresearch-menu">
      <a href="<?=$this->url('myresearch-changepassword') ?>" class="<?=$this->active == 'newpassword' ? ' active' : ''?>">
        <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
      </a>
    </div>
  <? else: ?>
    <div class="myresearch-menu">
      <a href="<?=$this->url('myresearch-changepasswordlink') ?>" class="<?=$this->active == 'newpasswordlink' ? ' active' : ''?>">
        <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
      </a>
    </div>
  <? endif; ?>
</div>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="myresearch-menu">
  <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login" class="<?=$this->active == 'history' ? ' active' : ''?>">
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches_tab')?>
    </a>
  <? endif; ?>
    <a href="<?=$this->url('myresearch-favorites')?>" class="<?=$this->active == 'favorites' ? ' active' : ''?>">
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', ['id' => $list['id']])?>" class="<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <?=$this->escapeHtml($list['title'])?>
          <span class="badge"><?=$list->cnt?></span>
        </a>
    <? endforeach; ?>
    <a href="<?=$this->url('editList', ['id'=>'NEW'])?>" class="">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<? endif ?>
