<?php
    // Set up page title:
    $this->headTitle($this->translate('Provided Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Provided Items') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody')?>">
  <h2><?= $this->transEsc('Provided Items')?></h2>
  <?= $this->flashmessages()?>

  <?= $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (!empty($this->transactions)): ?>
    <?php if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals">
      <div class="toolbar">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
            <?= $this->transEsc('select_page')?> |
          </label>
          <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?= $this->transEsc("renew_selected")?>" />
          <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?= $this->transEsc('renew_all')?>" />
        </div>
      </div>
    <?php endif; ?>

    <?php if ($paginator): ?>
      <?php
        $end = min(
          $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
          $paginator->getTotalItemCount()
        );
        $transParams = [
          '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
          '%%end%%'   => $this->localizedNumber($end),
          '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount()),
          '%%subject%%' => $this->transEsc('Provided Items'),
        ];
      ?>
      <?= $this->translate('showing_items_of_for_html', $transParams); ?>
    <?php endif; ?>

    <?php foreach ($hiddenTransactions as $ilsDetails): ?>
      <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
        <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <?php $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
        <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
          <div class="alert alert-success"><?= $this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
        <?php else: ?>
          <div class="alert alert-danger"><?= $this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?= $this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
        <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
        <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
      <?php endif; ?>
    <?php endforeach; ?>

    <?php $i = 0; foreach ($this->transactions as $resource): ?>
      <hr/>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <div id="record<?= $this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
        <?php if ($this->renewForm): ?>
          <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
            <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
            <div class="col-xs-1">
              <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?= $safeId?>" />
              <input type="hidden" name="selectAllIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              <input type="hidden" name="renewAllIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            </div>
          <?php else: ?>
            <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?= $this->escapeHtmlAttr($ilsDetails['renew_details'])?>" disabled="disabled" />
            </div>
          <?php endif; ?>
        <?php endif; ?>

        <div class="col-sm-9">
          <?php
            // If this is a non-missing Solr record, we should display a link:
            if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
              $title = $this->record($resource)->getTitleHtml();
              echo '<a href="' . $this->recordLink()->getUrl($resource) .
                '" class="title truncate">' . $title . '</a>';
            } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
              // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
              echo $this->escapeHtml($ilsDetails['title']);
              echo '<br />';
            } else {
              // Last resort -- indicate that no title could be found.
              echo $this->transEsc('Title not available');
              echo '<br />';
            }
          ?>
          <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
            <?= $this->transEsc('by')?>:
            <a href="<?= $this->record($resource)->getLink('author', $listAuthors[0])?>"><?= $this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?= $this->transEsc('more_authors_abbrev')?><?php endif; ?><br/>
          <?php endif; ?>
          <?php if (!empty($ilsDetails['volume'])): ?>
            <strong><?= $this->transEsc('Volume')?>:</strong> <?= $this->escapeHtml($ilsDetails['volume'])?>
            <br />
          <?php endif; ?>

          <?php if (isset($ilsDetails['callnumber'])) : ?>
            <strong><?= $this->transEsc('sort_callnumber')?>:</strong> <?= $this->escapeHtml($ilsDetails['callnumber'])?>
            <br />
          <?php endif; ?>

          <?php $showStatus = true; ?>

          <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
             value to display... */ ?>
          <?php $pickupDisplay = ''; ?>
          <?php $pickupTranslate = false; ?>
          <?php if (isset($ilsDetails['location'])): ?>
            <?php if ($this->pickup): ?>
              <?php foreach ($this->pickup as $library): ?>
                <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                  <?php $pickupDisplay = $library['locationDisplay']; ?>
                  <?php $pickupTranslate = true; ?>
                <?php endif; ?>
              <?php endforeach; ?>
            <?php endif; ?>
            <?php if (empty($pickupDisplay)): ?>
              <?php $pickupDisplay = $ilsDetails['location']; ?>
            <?php endif; ?>
          <?php endif; ?>
          <?php if (!empty($pickupDisplay)): ?>
            <strong><?= $this->transEsc('pick_up_location') ?>:</strong>
            <?= $pickupTranslate ? $this->transEscWithPrefix('location_', $pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
            <br />
          <?php endif; ?>

          <?php if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
            <div class="alert alert-info"><?= $this->transEsc($ilsDetails['message'])?></div>
          <?php endif; ?>
        </div>
      </div>
    <?php endforeach; ?>
    <hr/>
    <?php if ($this->renewForm): ?></form><?php endif; ?>
    <?= $paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
  <?php else: ?>
    <?= $this->transEsc('There are no items provided for pickup')?>.
  <?php endif; ?>
</div>

<div class="<?= $this->layoutClass('sidebar')?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'provided'])?>
</div>
