<?
    // Set up page title:
    $this->headTitle($this->translate('Provided Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Your Provided Items')?></h2>
    <?=$this->flashmessages()?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

    <? if (!empty($this->transactions)): ?>
      <? if ($this->renewForm): ?>
      <form name="renewals" method="post" id="renewals">
        <div class="toolbar">
          <div class="checkbox">
            <label>
              <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
              <?=$this->transEsc('select_page')?> |
            </label>
            <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
            <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
          </div>
        </div>
      <? endif; ?>

      <? if ($paginator): ?>
        <?=$this->transEsc("Showing")?>
        <? $start = $paginator->getAbsoluteItemNumber(1);
           $end = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
           $total = $paginator->getTotalItemCount();
        ?>
        <strong><?=$this->localizedNumber($start)?></strong> - <strong><?=$this->localizedNumber($end > $total ? $total : $end)?></strong>
        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($total)?></strong>
      <? endif; ?>

      <? foreach ($hiddenTransactions as $ilsDetails): ?>
        <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
          <? $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
          <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
          <? else: ?>
            <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
          <? endif; ?>
        <? endif; ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <? endif; ?>
      <? endforeach; ?>

      <? $i = 0; foreach ($this->transactions as $resource): ?>
        <hr/>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
          <? if ($this->renewForm): ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <div class="col-xs-1">
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
                <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
                <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              </div>
            <? else: ?>
              <div class="col-xs-1">
                  <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" disabled="disabled" />
              </div>
            <? endif; ?>
          <? endif; ?>
          
          <div class="col-sm-9">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $this->record($resource)->getTitleHtml();
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title truncate">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
                echo '<br />';
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
                echo '<br />';
              }
            ?>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['callnumber'])) : ?>
              <strong><?=$this->transEsc('sort_callnumber')?>:</strong> <?=$this->escapeHtml($ilsDetails['callnumber'])?>
              <br />
            <? endif; ?>

            <? $showStatus = true; ?>
            
            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($this->pickup): ?>
                <? foreach ($this->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEsc('location_' . $pickupDisplay, null, $pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br />
            <? endif; ?>

            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>
          </div>
        </div>
      <? endforeach; ?>
      <hr/>
      <? if ($this->renewForm): ?></form><? endif; ?>
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
    <? else: ?>
      <?=$this->transEsc('There are no items provided for pickup')?>.
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'provided'])?>
  </div>
</div>
