<h2><?= $this->transEsc('storage_retrieval_request_journal'); ?></h2>

<?= $this->flashmessages() ?>

<div class="journal-request">
  <form action="/Request/Journal/<?= $recordId; ?>" method="post">
    <h4><?= $this->transEsc('User data'); ?></h4>
    <div class="user-data">
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('Email'); ?>:</span>
        <span class="form-information"><?= $formData['email']; ?></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('Name'); ?>:</span>
        <span class="form-information"><?= $formData['name']; ?></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('Username'); ?>:</span>
        <span class="form-information"><?= $formData['username']; ?></span>
      </div>
    </div>

    <h4><?= $this->transEsc('Request data'); ?></h4>
    <div class="request-data">
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('Title'); ?>:</span>
        <span class="form-information"><?= $formData['title']; ?></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('storage_retrieval_request_select_location'); ?>:</span>
        <div class="form-data">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>&nbsp;</th>
              <th class="table-location"><?= $this->transEsc('Location'); ?></th>
              <th class="table-callnumber"><?= $this->transEsc('Call Number'); ?></th>
              <th class="table-item-chronology"><?= $this->transEsc('Item Chronology'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($inventory as $item): ?>
              <?php $checked = $item['callnumber'] == $formData['callnumber'] ?>
              <tr>
                <td>
                  <input type="radio" name="callnumber" value="<?= $item['callnumber']; ?>"<?= $checked ? ' checked="checked"' : ''; ?> />
                </td>
                <td class="table-location"><?= $item['location']; ?></td>
                <td class="table-callnumber"><?= $item['callnumber']; ?></td>
                <td class="table-item-chronology"><?= $item['chronology']; ?></td>
              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('storage_retrieval_request_year'); ?>:</span>
        <span class="form-data"><input id="edition" name="year" type="text" value="<?= $formData['year']; ?>"/></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('storage_retrieval_request_volume'); ?>:</span>
        <span class="form-data"><input id="year" name="volume" type="text" value="<?= $formData['volume']; ?>"/></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('storage_retrieval_request_page(s)'); ?>:</span>
        <span class="form-data"><input id="edition" name="pages" type="text" value="<?= $formData['pages'] ?? ''; ?>"/></span>
      </div>
      <div class="flex-group">
        <span class="form-description"><?= $this->transEsc('Note'); ?>:</span>
        <span class="form-data"><textarea id="comment" name="comment" rows="7"><?= $formData['comment']; ?></textarea></span>
      </div>
    </div>
    <div class="form-submit">
      <input type="submit" class="btn btn-primary" value="<?= $this->transEsc('Submit'); ?>">
    </div>
  </form>
</div>
