<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews();
     $this->jsTranslations()->addStrings(array('truncate_more' => 'truncate_more', 'truncate_less' => 'truncate_less'));
  ?>
  

<? /*
    P I C
*/ ?>

  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-2 img-col" style="margin-top:20px;">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>


<? /*
    C O R E M E T A D A T A
*/ ?>

  <div class="col-sm-10 info-col">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

    <?=$this->record($this->driver)->renderTemplate('core-titleHeadline.phtml')?>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p class="truncate"><?=$summary?></p>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <?
      $formatter = $this->recordDataFormatter();
      $metadataFields = $formatter->getData($driver, $formatter->getDefaults('full'));
    ?>
    <? if (!empty($metadataFields)): ?>
      <table class="table table-responsive" summary="<?=$this->transEsc('Bibliographic Details')?>">
          <colgroup>
            <col class="col-xs-4 col-sm-3 col-md-3">
            <col class="col-xs-8 col-sm-9 col-md-10">
        </colgroup>
        <? foreach ($metadataFields as $key => $current): ?>
          <tr><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
        <? endforeach; ?>
      </table>
    <? endif; ?>
    <?/* End Main Details */?>
  </div>
</div>
