<?php
    $publications = [];
    $i = 0;
?>
<? foreach ($data as $field): ?>
  <? $publications[$i] = '<span property="publisher" typeof="Organization">'; ?>
  <? $publications[$i] .= (!empty($field->getPlace())) ? '<span property="location">' . $field->getPlace() . '</span>' : ''; ?>
  <? $publications[$i] .= (!empty($field->getPlace()) && !empty($field->getName())) ? ' : ' : ''; ?>
  <? $publications[$i] .= (!empty($field->getName())) ? '<span property="name">' . $field->getName() . '</span>' : ''; ?>
  <? $publications[$i] .= '</span>'; ?>
  <? $publications[$i] .= ((!empty($field->getPlace()) || !empty($field->getName())) && !empty($field->getDate())) ? ', ' : ''; ?>
  <? $publications[$i] .= (!empty($field->getDate())) ? '<span property="publicationDate">' . $field->getDate() . '</span>' : ''; ?>
  <? $i++; ?>
<? endforeach; ?>
<?=implode('; ', $publications)?>