<? foreach ($data as $field): ?>
  <?/* Depending on the record driver, $field may either be an array with
     "name" and "number" keys or a flat string containing only the series
     name.  We should account for both cases to maximize compatibility. */?>
  <? if (is_array($field)): ?>
    <? if (!empty($field['name'])): ?>
      <? if ($field['id']) : ?>
        <? $url = $this->recordLink()->related(['type' => 'bib', 'value' => $field['id']]); ?>
        <a href="<?=$url?>"><?=$this->escapeHtml($field['name'])?></a>
      <? else: ?>
        <?=$this->escapeHtml($field['name'])?>
      <? endif; ?>
      <? if (!empty($field['number'])): ?>
        <?=$this->escapeHtml($field['number'])?>
      <? endif; ?>
      <br/>
    <? endif; ?>
  <? else: ?>
    <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
  <? endif; ?>
<? endforeach; ?>
