<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $cart = $this->cart();
  $cartId = $this->driver->getSourceIdentifier() . '|' . $this->driver->getUniqueId();
?>
<ul class="record-nav nav nav-pills hidden-print pull-right" style="padding-top: 15px;">
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
    <li><a title="<?=$this->transEsc('Cite this')?>" class="cite-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" rel="nofollow"><i class="fa fa-quote-left" aria-hidden="true"></i></a></li>
  <? endif; ?>
  <? if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
    <li><a title="<?=$this->transEsc('Text this')?>" class="sms-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" rel="nofollow"><i class="fa fa-mobile" aria-hidden="true"></i></a></li>
  <? endif; ?>
  <li><a title="<?=$this->transEsc('Email this')?>" class="mail-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" rel="nofollow"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown">
      <a title="<?=$this->transEsc('Export Record') ?>" class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" rel="nofollow"><i class="fa fa-share" aria-hidden="true"></i></a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>

  <? if ($cart->isActive()): ?>
    <li class="bookbag-menu">
      <input class="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a title="<?=$this->transEsc('Add to Book Bag') ?>" href="#" class="cart-add hidden<? if(!$cart->contains($cartId)): ?> correct<? endif ?>">
        <i class="fa fa-plus-square" aria-hidden="true"></i></a>
      <a title="<?=$this->transEsc('Remove from Book Bag') ?>" href="#" class="cart-remove hidden<? if($cart->contains($cartId)): ?> correct<? endif ?>">
        <i class="fa fa-minus-square" aria-hidden="true"></i></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-thulb" type="submit" name="delete" title="<?=$this->transEsc('Remove from Book Bag')?>"><i class="fa fa-minus-square" aria-hidden="true"></i></input>
          <? else: ?>
            <input class="btn btn-thulb" type="submit" name="add" title="<?=$this->transEsc('Add to Book Bag')?>"><i class="fa fa-plus-square" aria-hidden="true"></i></input>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
</ul>