<?php
  // Set up page title:
  $lookfor = $this->results->getUrlQuery()->isQuerySuppressed() ? '' : $this->params->getDisplayQuery();
  if (isset($this->overrideTitle)) {
      $this->headTitle($this->overrideTitle);
  } else {
      $this->headTitle($this->translate('Search Results') . (empty($lookfor) ? '' : " - {$lookfor}"));
  }

  // Set up breadcrumbs:
  if (isset($this->overrideTitle)) {
    $this->layout()->breadcrumbs .= '<li class="active">' . $this->escapeHtml($this->overrideTitle) . '</li>';
  } else {
    $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('Search') . ': ' . $this->escapeHtml($lookfor) . '</li>';
  }

  // Enable cart if appropriate:
  $this->showCartControls = $this->params->getOptions()->supportsCart() && $this->cart()->isActive();
  // Enable bulk options if appropriate:
  $this->showBulkOptions = $this->params->getOptions()->supportsCart() && $this->showBulkOptions;

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != "full") {
    $this->headScript()->appendFile("record.js");
    $this->headScript()->appendFile("embedded_record.js");
  }

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  
  
  $this->overrideTitle = $this->translate('View Records');
  $this->overrideSearchHeading = '';

  // Disable top search box -- it doesn't make sense in this module.
  $this->layout()->searchbox = false;
?>

<img src="/themes/thulb/images/Ajax-loader.gif"
     id="img-load" />
<div id="searchcontent">
  <div id="overlay" class="col-xs-12">
    <p>&nbsp;</p>
  </div>
  <div class="col-xs-12">
    <div id="resultlist">
        <?php if (($recordTotal = $this->results->getResultTotal()) > 0): // only display these at very top if we have results ?>
          <?php foreach ($this->results->getRecommendations('top') as $current): ?>
            <?= $this->recommend($current)?>
          <?php endforeach; ?>
        <?php endif; ?>
        <?= $this->flashmessages()?>

        <?php if ($recordTotal < 1): ?>
          <p>
            <?php if (isset($this->overrideEmptyMessage)): ?>
              <?= $this->overrideEmptyMessage?>
            <?php else: ?>
                <?php $this->layout()->srmessage = $this->translate('nohit_lookfor_html', ['%%lookfor%%' => $this->escapeHtml($lookfor)]); ?>
                <?= $this->layout()->srmessage ?>
            <?php endif; ?>
          </p>
          <?php if (isset($this->parseError)): ?>
            <p class="alert alert-danger"><?= $this->transEsc('nohit_parse_error')?></p>
          <?php endif; ?>
          <?php foreach (($top = $this->results->getRecommendations('top')) as $current): ?>
            <?= $this->recommend($current)?>
          <?php endforeach; ?>
          <?php foreach ($this->results->getRecommendations('noresults') as $current): ?>
            <?php if (!in_array($current, $top)): ?>
              <?= $this->recommend($current)?>
            <?php endif; ?>
          <?php endforeach; ?>
        <?php else: ?>
        
          <form class="form-inline" method="post" name="bulkActionForm" action="<?= $this->url('cart-searchresultsbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
            <div class="row hidden-print">
              <div class="col-xs-12">
                <div class="pull-right">
                <?= $this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results, 'options' => isset($this->paginationOptions) ? $this->paginationOptions : []])?>
                </div>
              </div>
            </div>

            <?= $this->render('search/list-' . $this->params->getView() . '.phtml')?>

            <div class="row hidden-print">
              <div class="col-xs-12">
                <div class="pull-right">
                <?= $this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results, 'options' => isset($this->paginationOptions) ? $this->paginationOptions : []])?>
                </div>
              </div>
            </div>
          </form>
        <?php endif; ?>
    </div>
  </div>
  <?php /* End Main Listing */ ?>

</div>