<?
  // Set up page title:
  $lookfor = $this->results->getUrlQuery()->isQuerySuppressed() ? '' : $this->params->getDisplayQuery();
  if (isset($this->overrideTitle)) {
      $this->headTitle($this->overrideTitle);
  } else {
      $this->headTitle($this->translate('Search Results') . (empty($lookfor) ? '' : " - {$lookfor}"));
  }

  // Set up breadcrumbs:
  if (isset($this->overrideTitle)) {
    $this->layout()->breadcrumbs .= '<li class="active">' . $this->escapeHtml($this->overrideTitle) . '</li>';
  } else {
    $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc('Search') . ': ' . $this->escapeHtml($lookfor) . '</li>';
  }

  // Enable cart if appropriate:
  $this->showCartControls = $this->params->getOptions()->supportsCart() && $this->cart()->isActive();
  // Enable bulk options if appropriate:
  $this->showBulkOptions = $this->params->getOptions()->supportsCart() && $this->showBulkOptions;

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != "full") {
    $this->headScript()->appendFile("record.js");
    $this->headScript()->appendFile("embedded_record.js");
  }

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  
  
  $this->overrideTitle = $this->translate('View Records');
  $this->overrideSearchHeading = '';

  // Disable top search box -- it doesn't make sense in this module.
  $this->layout()->searchbox = false;
?>

<img src="/vufind/themes/thulb/images/Ajax-loader.gif"
     id="img-load" />
<div id="searchcontent" class="row">
  <div id="overlay" class="col-xs-12">
    <p>&nbsp;</p>
  </div>
  <div class="col-xs-12">
    <div id="resultlist">
        <? if (($recordTotal = $this->results->getResultTotal()) > 0): // only display these at very top if we have results ?>
          <? foreach ($this->results->getRecommendations('top') as $current): ?>
            <?=$this->recommend($current)?>
          <? endforeach; ?>
        <? endif; ?>
        <?=$this->flashmessages()?>

        <? if ($recordTotal < 1): ?>
          <p>
            <? if (isset($this->overrideEmptyMessage)): ?>
              <?=$this->overrideEmptyMessage?>
            <? else: ?>
              <? $this->layout()->srmessage = $this->transEsc('nohit_prefix') . ' - ' . $this->escapeHtml($lookfor) . ' - ' . $this->transEsc('nohit_suffix'); ?>
              <?=$this->layout()->srmessage ?>
            <? endif; ?>
          </p>
          <? if (isset($this->parseError)): ?>
            <p class="alert alert-danger"><?=$this->transEsc('nohit_parse_error')?></p>
          <? endif; ?>
          <? foreach (($top = $this->results->getRecommendations('top')) as $current): ?>
            <?=$this->recommend($current)?>
          <? endforeach; ?>
          <? foreach ($this->results->getRecommendations('noresults') as $current): ?>
            <? if (!in_array($current, $top)): ?>
              <?=$this->recommend($current)?>
            <? endif; ?>
          <? endforeach; ?>
        <? else: ?>
        
          <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
            <div class="row hidden-print">
              <div class="col-xs-12">
                <div class="pull-right">
                <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results, 'options' => isset($this->paginationOptions) ? $this->paginationOptions : []])?>
                </div>
              </div>
            </div>

            <?=$this->render('search/list-' . $this->params->getView() . '.phtml')?>

            <div class="row hidden-print">
              <div class="col-xs-12">
                <div class="pull-right">
                <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results, 'options' => isset($this->paginationOptions) ? $this->paginationOptions : []])?>
                </div>
              </div>
            </div>
          </form>
        <? endif; ?>
    </div>
  </div>
  <? /* End Main Listing */ ?>

</div>