<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <? if ($useHiddenFilters): ?>
      <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <? endif; ?>

    <select id="sort_options_1" name="sort" class="jumpMenu form-control">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
