<? $list = $this->params->getSortList(); if (!empty($list)): ?>
<div class="list-group facet">
  <div class="list-group-item">
    <?=$this->transEsc('Sort')?>
  </div>
  <div class="list-group-item">
  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <select id="sort_options_1" name="sort" class="jumpMenu form-control">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
  </div>
</div>
<? endif; ?>