<?php $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="form-inline" action="<?= $this->currentPath()?>" method="get" name="sort">
    <?php if (isset($useHiddenFilters) && $useHiddenFilters): ?>
      <?= $this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <?php endif; ?>

    <select id="sort_options_1" name="sort" class="jumpMenu form-control">
      <?php foreach ($list as $sortType => $sortData): ?>
        <option value="<?= $this->escapeHtmlAttr($sortType)?>"<?= $sortData['selected']?' selected="selected"':''?>><?= $this->transEsc($sortData['desc'])?></option>
      <?php endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?= $this->transEscAttr("Set")?>" /></noscript>
  </form>
<?php endif; ?>
