<?php
  // Set up convenience variables:
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $openUrl = $this->openUrl($this->tab->getRecordDriver(), 'holdings');
  $openUrlActive = $openUrl->isActive();

  // Account for replace_other_urls setting
  $offlineMode = $this->ils()->getOfflineMode();
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
  $citesLink = is_callable([$this->driver, 'getCitatedReferencesLink']) ? $this->driver->getCitatedReferencesLink() : false;
  $citesCount = is_callable([$this->driver, 'getCitatedReferencesCount']) ? $this->driver->getCitatedReferencesCount() : false;

  try {
    $holdings = $this->driver->getHoldings();
  }
  catch (\VuFind\Exception\ILS $e) {
    $holdings = ['holdings' => []];
    $offlineMode = 'ils-offline';
  }

  $doiHtml = $this->context($this)->renderInContext('Helpers/doi-linker.phtml', ['location' => 'holdings']);
?>

<?= $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
      <?= $this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?php // ILS offline ?>
<?= ($offlineMode == "ils-offline" && empty($holdings)) ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php // unused ??? ?>
<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?= $this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?= $this->transEsc("Login")?></a> <?= $this->transEsc("hold_login")?>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?= $this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?php // unused ??? ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?= $this->transEsc('request_place_text')?>" href="<?= $this->recordLink()->getRequestUrl($holdingTitleHold)?>">
    <i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?= $this->transEsc('title_hold_place')?>
  </a>
<?php endif; ?>

<?php // online holdings ?>
<?php $onlineHolding = $holdings['holdings']['Remote'] ?? []; ?>
<?php if(!empty($onlineHolding) || !empty($doiHtml)): ?>
  <table class="table table-striped" summary="<?= $this->transEsc('Holdings details from')?> <?= $this->transEsc('Remote')?>">
    <?php if(!empty($doiHtml)): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <td>
          <dl class="dl-horizontal">
            <dt><?= $doiHtml; ?></dt>
            <dd><?= $this->translate('explain_unpaywall'); ?></dd>
          </dl>
        </td>
      </tr>
    <?php endif; ?>
    <?php if(!empty($onlineHolding)):
      foreach ($onlineHolding['items'] as $row): ?>
        <tr vocab="http://schema.org/" typeof="Offer">
          <td>
            <dl class="dl-horizontal">
              <dt>
                <a href="<?php echo $row['remotehref']; ?>" target="_blank" class="btn btn-primary external-link">
                  <?= $desc = $this->transEsc($row['remotedesc'] ?? 'Get full text'); ?>
                </a>
              </dt>
              <dd>
                <?php if(!empty($row['remotetitle'])):?>
                  [<?php echo $row['remotetitle']; ?>]
                <?php endif; ?>

                <?php /* BESTANDSANGABEN */ ?>
                <?php $chron = $this->thulb_holdingHelper()->getHoldingChronology($row); ?>
                <?php if (!empty($chron)) : ?>
                  <div class="item-notes">
                    <?php if (is_array($chron) && count($chron) > 0): ?>
                      <?php foreach ($chron as $chron): ?>
                        <?php if (!empty($chron)): ?>
                          <p><?= $chron ?></p>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    <?php endif; ?>
                  </div>
                <?php endif; ?>

                <?php /* ANMERKGUNGEN */ ?>
                <?php $comments = $this->thulb_holdingHelper()->getHoldingComments($row); ?>
                <?php if (!empty($comments)) : ?>
                  <div class="item-notes">
                    <?php if (is_array($comments) && count($comments) > 0): ?>
                      <?php foreach ($comments as $comment): ?>
                        <?php if (!empty($comment)): ?>
                          <p><?= $comment ?></p>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    <?php endif; ?>
                  </div>
                <?php endif; ?>

                <?php if(isset($row['remotedesc']) && $row['remotedesc'] === $this->transEsc('get_citation')): ?>
                  <div class="item-notes">
                    <?= $this->transEsc('explain_reference') ?>
                  </div>
                <?php endif; ?>

                <?php if ($citesLink && $citesCount > 0) : ?>
                  <div class="citations">
                    <?= $citesCount?>
                    <a href="<?= $citesLink?>" target="_blank" class="external-link">
                      <?= $this->transEsc('Web of Science Scites Link')?>
                    </a>
                    <?= $this->translate('Web of Science Scites Ref')?>
                  </div>
                <?php endif; ?>
              </dd>
            </dl>
          </td>
        </tr>
      <?php endforeach; ?>
    <?php endif; ?>
  </table>
<?php endif; ?>

<?php // physical holdings ?>
<?php if (!empty($holdings)): ?>
  <?php foreach ($holdings['holdings'] as $holdingKey => $holding): ?>
    <?php if($holdingKey == 'Remote') continue; ?>
    <h3>
      <?= $this->thulb_holdingHelper()->getLocation($holding, true);?>
    </h3>
    <table class="table table-striped" summary="<?= $this->transEsc('Holdings details from')?> <?= $this->transEsc($holding['location'])?>">
      <?php if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
        <tr>
            <?php // Translation for summary is a special case for backwards-compatibility ?>
          <th><?= $textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
          <td>
            <?php foreach ($textFields as $current): ?>
              <?= $this->escapeHtml($current)?><br/>
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endforeach; endif; ?>
      <?php foreach ($holding['items'] as $row): ?>
        <?php
        // AJAX Check record?
        $check = isset($row['check']) && $row['check'];
        $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
        $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
        ?>
        <?php if (isset($row['barcode']) && $row['barcode'] != ""): ?>
        <tr vocab="http://schema.org/" typeof="Offer">
          <td>
            <dl class="dl-horizontal">
              <?php $callno = $this->thulb_holdingHelper()->getCallnumber($row); ?>
              <?php if ($callno): ?>
                <dt><?= $this->transEsc("Call Number")?>:</dt>
                <dd><strong><?= $callno ?></strong></dd>
              <?php endif; ?>

              <?php if(!empty($row['remotehref']) && $holding['location'] == "Remote"): ?>
                <dt><?= $this->transEsc('Link')?>:</dt>
                <dd>
                  <a href="<?php echo $row['remotehref']; ?>" target="_blank" class="btn btn-primary">
                    <?= $this->transEsc($row['remotedesc'] ?? 'Full text online'); ?>
                  </a>
                  <?php if(!empty($row['remotetitle'])):?>
                    [<?php echo $row['remotetitle']; ?>]
                  <?php endif; ?>
                  <?php if(isset($row['remotedesc']) && $row['remotedesc'] === $this->transEsc('get_citation')): ?>
                    <div class="item-notes">
                      <?= $this->transEsc('explain_reference') ?>
                    </div>
                  <?php endif; ?>
                </dd>
                <?php if ($citesLink && $citesCount > 0) : ?>
                  <dd>
                    <div class="citations">
                      <?= $citesCount?> <a href="<?= $citesLink?>" target="_blank"><?= $this->transEsc('Web of Science Scites Link')?></a>
                      <?= $this->translate('Web of Science Scites Ref')?>
                    </div>
                  </dd>
                <?php endif; ?>
              <?php endif; ?>

              <!-- @TODO needed? -->
              <?php if(!empty($doiHtml)): ?>
                <dd><?= $doiHtml; ?></dd>
              <?php endif; ?>

              <?php /* ANMERKGUNGEN & BESTAND */ ?>
              <?php $comments = $this->thulb_holdingHelper()->getHoldingComments($row); ?>
              <?php $chron = $this->thulb_holdingHelper()->getHoldingChronology($row); ?>

              <?php if (!empty($chron)) : ?>
                <dt><?= $this->transEsc("Item Chronology")?>:</dt>
                <div class="item-notes">
                  <dd>
                    <?php if (is_array($chron) && count($chron) > 0): ?>
                      <ul>
                        <?php foreach ($chron as $chron): ?>
                          <?php if (!empty($chron)): ?>
                          <li><?= $chron ?></li>
                          <?php endif; ?>
                        <?php endforeach; ?>
                      </ul>
                    <?php endif; ?>
                  </dd>
                </div>
              <?php endif; ?>

              <?php if (!empty($comments)) : ?>
                <dt><?= $this->transEsc("Item Notes")?>:</dt>
                <div class="item-notes">
                  <dd>
                    <?php if (is_array($comments) && count($comments) > 0): ?>
                      <ul>
                        <?php foreach ($comments as $comment): ?>
                          <?php if (!empty($comment)): ?>
                          <li><?= $comment ?></li>
                          <?php endif; ?>
                        <?php endforeach; ?>
                      </ul>
                    <?php endif; ?>
                  </dd>
                </div>
              <?php endif; ?>

              <?php if(!empty($row['remotehref']) && $holding['location'] != "Remote"): ?>
                <dt><?= $this->transEsc('See also')?>:</dt>
                <dd>
                  <a href="<?php echo $row['remotehref']; ?>"><?php echo $row['remotedomain']; ?></a>
                    <?php if(!empty($row['remotetitle'])):?>
                      [<?php echo $row['remotetitle']; ?>]
                    <?php endif; ?>
                </dd>
              <?php endif; ?>

              <?php if ($holding['location'] != "Remote" && $callno != "Unknown" && $callno != "bestellt"): ?>
                <dt><?= $this->transEsc("Availability Status")?>:</dt>
                <dd><?= $this->thulb_holdingHelper()->getAvailability($row);?></dd>
              <?php endif; ?>
            </dl>
          </td>
        </tr>
        <?php endif; ?>
      <?php endforeach; ?>

      <?php if (!empty($holding['purchase_history'])): ?>
        <tr>
          <th><?= $this->transEsc("Most Recent Received Issues")?>:</th>
          <td>
            <?php foreach ($holding['purchase_history'] as $current): ?>
              <?= $this->escapeHtml($current['issue'])?><br/>
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>
    </table>
  <?php endforeach; ?>
<?php endif; ?>

<?php // unused ??? ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?= $this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?= $this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>

<?php if($this->driver->isFormat('Journal') && $this->record($this->driver)->hasNonArticleTab($this)): ?>
    <?= $this->transEsc('see volumes tab for listing and ordering of volumes'); ?>
<?php endif; ?>
