<?
  // Set page title.
  $this->headTitle($this->translate($this->tab->getDescription()) . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  try {
      $results = $this->tab->getResults();
      $params = $this->tab->getParams();
  } catch (\Exception $ex) {
      $results = false;
      $params = false;
  }
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];
  $this->jsTranslations()->addStrings(
        [
            'noHoldings' => 'see volumes tab for further holdings'
        ]
    );
?>
<? if ($results && $params && ($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <? foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <? endforeach; ?>
  <div class="clearfix hidden-print hidden-xs">
    <div class="pull-left flip">
      <?=$this->transEsc("Showing")?>
      <strong><?=$this->localizedNumber($results->getStartRecord())?></strong> - <strong><?=$this->localizedNumber($results->getEndRecord())?></strong>
      <? if (!isset($this->skipTotalCount)): ?>
        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($recordTotal)?></strong> <?=$this->transEsc('Items')?>
      <? endif; ?>
    </div>
    <div class="pull-right flip" style="max-width:225px;">
      <?=str_replace('/AjaxTab', '/ArticleCollectionList', $this->render('search/controls/limit.phtml', $searchDetails))?>
      <?=str_replace('/AjaxTab', '/ArticleCollectionList', $this->render('search/controls/sort.phtml', $searchDetails))?>
    </div>
  </div>
  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>">
    <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
    <?=str_replace('/AjaxTab', '/ArticleCollectionList', $this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results]))?>
  </form>
<? endif; ?>
