<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter();
    $mainFields = $formatter->getData($driver, $formatter->getDefaults('description'));
?>
<table class="table table-striped" summary="<?= $this->transEscAttr('Description')?>">
  <?php if (!empty($mainFields)): ?>
    <?php foreach ($mainFields as $key => $value): ?>
      <?php if ($key === 'DOI') : ?>
        <tr><th><?= $this->transEsc($key)?>:</th><td><a href="http://dx.doi.org/<?= $value?>" target="_blank"><?= $value?></a></td></tr>
      <?php else : ?>
        <tr><th><?= $this->transEsc($key)?>:</th><td><?= $value?></td></tr>
      <?php endif; ?>
    <?php endforeach; ?>
  <?php else: ?>
    <tr><td><?= $this->transEsc('no_description')?></td></tr>
  <?php endif; ?>
</table>
