<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $offlineMode = $this->ils()->getOfflineMode();
    
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());

    $doiHtml = $this->render('Helpers/doi.phtml', ['driver' => $this->driver, 'location' => 'holdings']);
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<? if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<? endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>

<?php if(!empty($doiHtml)): ?>
  <table class="table table-striped">
    <tr vocab="http://schema.org/" typeof="Offer">
      <td>
        <dl class="dl-horizontal">
          <dt><?=$this->transEsc('Link')?>:</dt>
          <dd><?=$doiHtml; ?></dd>
        </dl>
      </td>
    </tr>
  </table>
<?php endif; ?>

<? if ( !empty($holdings) ): ?>
  <? foreach ($holdings['holdings'] as $holding): ?>
    <? $holding_location = $this->thulb_holdingHelper()->getLocation($holding); ?>
    <h3>
      <?=$this->thulb_holdingHelper()->getLocation($holding);?>
    </h3>
    <table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
    <? if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
      <tr>
        <? // Translation for summary is a special case for backwards-compatibility ?>
        <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
        <td>
          <? foreach ($textFields as $current): ?>
            <?=$this->escapeHtml($current)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
    <? endforeach; endif; ?>
    <? foreach ($holding['items'] as $row): ?>
      <?
        // AJAX Check record?
        $check = isset($row['check']) && $row['check'];
        $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
        $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
      ?>
      <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
          <tr vocab="http://schema.org/" typeof="Offer">
            <td>
              <dl class="dl-horizontal">
                <? $callno = $this->thulb_holdingHelper()->getCallnumber($row); ?>
                <? if ($callno): ?>
                  <dt><?=$this->transEsc("Call Number")?>:</dt>
                  <dd><strong><?=$callno ?></strong></dd>
                <? endif; ?>

                  <?php if(!empty($row['remotehref']) && $holding['location'] == "Remote"): ?>
                    <dt><?=$this->transEsc('Link')?>:</dt>
                    <dd>
                      <a href="<?php echo $row['remotehref']; ?>" target="_blank"><?php echo $row['remotedomain']; ?></a>
                        <?php if(!empty($row['remotetitle'])):?>
                          [<?php echo $row['remotetitle']; ?>]
                        <?php endif; ?>
                    </dd>
                  <?php endif; ?>

                <? /* ANMERKGUNGEN & BESTAND */ ?>
                <? $comments = $this->thulb_holdingHelper()->getHoldingComments($row); ?>
                <? $chron = $this->thulb_holdingHelper()->getHoldingChronology($row); ?>

                <? if (!empty($chron)) : ?>
                  <dt><?=$this->transEsc("Item Chronology")?>:</dt>
                  <div class="item-notes">
                    <dd>
                      <? if (is_array($chron) && count($chron) > 0): ?>
                        <ul>
                          <? foreach ($chron as $chron): ?>
                            <? if (!empty($chron)): ?>
                              <li><?=$chron ?></li>
                            <? endif; ?>
                          <? endforeach; ?>
                        </ul>
                      <? endif; ?>
                    </dd>
                  </div>
                <? endif; ?>

                <? if (!empty($comments)) : ?>
                  <dt><?=$this->transEsc("Item Notes")?>:</dt>
                  <div class="item-notes">
                    <dd>
                    <? if (is_array($comments) && count($comments) > 0): ?>
                      <ul>
                        <? foreach ($comments as $comment): ?>
                          <? if (!empty($comment)): ?>
                            <li><?=$comment ?></li>
                          <? endif; ?>
                        <? endforeach; ?>
                      </ul>
                    <? endif; ?>
                    </dd>
                  </div>
                <? endif; ?>

                <?php if(!empty($row['remotehref']) && $holding['location'] != "Remote"): ?>
                  <dt><?=$this->transEsc('See also')?>:</dt>
                  <dd>
                    <a href="<?php echo $row['remotehref']; ?>"><?php echo $row['remotedomain']; ?></a>
                    <?php if(!empty($row['remotetitle'])):?>
                      [<?php echo $row['remotetitle']; ?>]
                  <?php endif; ?>
                  </dd>
                <?php endif; ?>

                <? if ($holding['location'] != "Remote" && $callno != "Unknown" && $callno != "bestellt"): ?>
                  <dt><?=$this->transEsc("Availability Status")?>:</dt>
                  <dd><?=$this->thulb_holdingHelper()->getAvailability($row);?></dd>
                <? endif; ?>
              </dl>
            </td>
          </tr>
      <? endif; ?>
    <? endforeach; ?>

    <? if (!empty($holding['purchase_history'])): ?>
      <tr>
        <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
        <td>
          <? foreach ($holding['purchase_history'] as $current): ?>
            <?=$this->escapeHtml($current['issue'])?><br/>
          <? endforeach; ?>
        </td>
      </tr>
    <? endif; ?>
    </table>
  <? endforeach; ?>
<? endif; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>