<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th width="20%">
                <?=$this->transEsc("ils_hold_item_status")?>
            </th>
            <th width="40%">
                <?=$this->transEsc("ils_hold_item_location")?>
            </th>
            <th width="40%">
                <?=$this->transEsc("Call Number")?>
            </th>
        </tr>
    </thead>
    <tbody>
        <? foreach ($holdings as $holding): ?>
            <? foreach ($holding['items'] as $row): ?>
                <tr>
                    <td>
                            <?
                                // AJAX Check record?
                                $check = isset($row['check']) && $row['check'];
                                $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
                                $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
                                // AJAX block record?
                                $block = !$check && isset($row['addLink']) && $row['addLink'] === 'block';
                                $blockStorageRetrievalRequest = !$checkStorageRetrievalRequest && isset($row['addStorageRetrievalRequestLink']) && $row['addStorageRetrievalRequestLink'] === 'block';
                                $blockILLRequest = !$checkILLRequest && isset($row['addILLRequestLink']) && $row['addILLRequestLink'] === 'block';
                            ?>
                            <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
                                <? if ($row['reserve'] == "Y"): ?>
                                    <link property="availability" href="http://schema.org/InStoreOnly" />
                                    <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
                                <? endif; ?>
                                <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
                                    <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
                                <? else: ?>
                                    <? if ($row['availability']): ?>
                                        <? /* Begin Available Items (Holds) */ ?>
                                        <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
                                        <? if (!$block && isset($row['link']) && $row['link']): ?>
                                            <a class="<?=$check ? 'checkRequest ' : ''?>placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
                                        <? endif; ?>
                                        <? if (!$blockStorageRetrievalRequest && isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                                            <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
                                        <? endif; ?>
                                        <? if (!$blockILLRequest && isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                                            <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
                                        <? endif; ?>
                                    <? else: ?>
                                        <? /* Begin Unavailable Items (Recalls) */ ?>
                                        <span class="text-danger"><?=$this->transEsc('ils_hold_item_' . $row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
                                        <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
                                        <? if (isset($row['duedate']) && $row['duedate']): ?>
                                            &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
                                        <? endif; ?>
                                        <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                                            <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
                                        <? endif; ?>
                                        <? if (!$block && isset($row['link']) && $row['link']): ?>
                                            <a class="<?=$check ? 'checkRequest' : ''?> placehold" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
                                        <? endif; ?>
                                    <? endif; ?>
                                <? endif; ?>
                                <? /* Embed item structured data: library, barcode, call number */ ?>
                                <? if ($row['location']): ?>
                                    <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
                                <? endif; ?>
                                <? if ($row['barcode']): ?>
                                    <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
                                <? endif; ?>
                                <? if ($row['callnumber']): ?>
                                    <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
                                <? endif; ?>
                                <? /* Declare that the item is to be borrowed, not for sale */ ?>
                                <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
                                <link property="itemOffered" href="#record" />
                            <? endif; ?>
                    </td>
                    <td>
                        <? $locationText = $this->transEsc('location_' . $holding['location'], [], $holding['location']); ?>
                        <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
                            <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
                        <? else: ?>
                            <?=$locationText?>
                        <? endif; ?>
                    </td>
                    <td>
                        <? $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
                            <? foreach ($callNos as $callNo): ?>
                                <? if ($this->callnumberHandler): ?>
                                    <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
                                <? else: ?>
                                    <?=$this->escapeHtml($callNo)?>
                                <? endif; ?>
                                <br />
                            <? endforeach; ?>
                        <? else: ?>
                            &nbsp;
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
        <? endforeach; ?>
    </tbody>
</table>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>
