<?
  // Set page title.
  $this->headTitle($this->translate($this->tab->getDescription()) . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  $results = $this->tab->getResults();
  $params = $this->tab->getParams();
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];
  $this->jsTranslations()->addStrings(
        [
            'noHoldings' => 'see volumes tab for further holdings'
        ]
    );
?>
<? if (($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <? foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <? endforeach; ?>
  <div class="clearfix hidden-print">
    <div class="pull-left flip">
      <?
        $transParams = [
          '%%start%%' => $this->localizedNumber($results->getStartRecord()),
          '%%end%%'   => $this->localizedNumber($results->getEndRecord()),
          '%%total%%' => $this->localizedNumber($recordTotal)
        ];
      ?>
      <? if (!isset($this->skipTotalCount)): ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      <? else: ?>
        <?=$this->translate('showing_items_html', $transParams); ?>
      <? endif; ?>
    </div>
    <div class="pull-right flip">
      <?=str_replace('/AjaxTab', '/NonArticleCollectionList', $this->render('search/controls/limit.phtml', $searchDetails))?>
      <?=str_replace('/AjaxTab', '/NonArticleCollectionList', $this->render('search/controls/sort.phtml', $searchDetails))?>
    </div>
  </div>
  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>">
    <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
    <?=str_replace('/AjaxTab', '/NonArticleCollectionList', $this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results]))?>
  </form>
<? endif; ?>