<?
  // Set page title.
  $this->headTitle($this->translate($this->tab->getDescription()) . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  try {
      $results = $this->tab->getResults();
      $params = $this->tab->getParams();
  } catch (\Exception $ex) {
      $results = false;
      $params = false;
  }
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];
?>
<? if ($results && $params && ($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <? foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <? endforeach; ?>
  <div class="clearfix hidden-print">
    <?php if($recordTotal > 0): ?>
      <div class="pull-left flip">
        <?
          $transParams = [
            '%%start%%' => $this->localizedNumber($results->getStartRecord()),
            '%%end%%'   => $this->localizedNumber($results->getEndRecord()),
            '%%total%%' => $this->localizedNumber($recordTotal)
          ];
        ?>
        <? if (!isset($this->skipTotalCount)): ?>
          <?=$this->translate('showing_items_of_html', $transParams); ?>
        <? else: ?>
          <?=$this->translate('showing_items_html', $transParams); ?>
        <? endif; ?>
      </div>
      <div class="pull-right flip">
        <?=$this->render('search/controls/limit.phtml', $searchDetails)?>
        <?=$this->render('search/controls/sort.phtml', $searchDetails)?>
      </div>
    <?endif; ?>
    <?php if($this->driver->isFormat('Journal') && $this->driver->isInArchive()): ?>
      <div class="journal-not-found flex-center center-text">
        <span style="margin-right: 15px"><?= $this->transEsc('storage_retrieval_request_volume_not_listed'); ?></span>
        <a href="/Request/Journal/<?=$this->driver->getUniqueId(); ?>" data-lightbox class="btn btn-primary"><?= $this->transEsc('storage_retrieval_request_order_here');?></a>
      </div>
    <?php endif; ?>
  </div>
  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>">
    <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
    <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results])?>
  </form>
<?php elseif($this->driver->isFormat('Journal') && $this->driver->isInArchive()): ?>
  <div class="journal-not-found flex-center center-text">
    <span style="margin-right: 15px"><?= $this->transEsc('storage_retrieval_request_volume_not_listed'); ?></span>
    <a href="/Request/Journal/<?=$this->driver->getUniqueId(); ?>" data-lightbox class="btn btn-primary"><?= $this->transEsc('storage_retrieval_request_order_here');?></a>
  </div>
<? endif; ?>