<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
  <?
  $ilsStatusScript = <<<JS
      $(document).ready(function() {
        $.ajax({
            dataType: 'json',
            method: 'GET',
            data: {'offlineModeMsg':'ils_offline_home_message'},
            url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
            success: function(response) {
                $('.searchHomeContent').append(response.data);
            }
        });
      });
JS;
  ?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET'); ?>

  <div class="row startpage_logo">
    <div class="col-sm-4 col-sm-offset-4">
      <img alt="welcome thulbsuche" src="<?=$this->imageLink('thulbsuche_l.png')?>">
    </div>
  </div>
  <div class="row startpage_searchbox">
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
  </div>

  <div class="row tutorial">
    <div class="col-sm-4 col-xs-12 tutorial_sub">
        <h1>1.</h1>
        <h5>Was suchst Du?</h5>
        Wähle vorab in welchem Feld du suchen möchtest.
        <img alt="tutorial step1" src="<?=$this->imageLink('Tut_SearchBox.png')?>">
    </div>
    <div class="col-sm-4 col-xs-12 tutorial_sub">
        <h1>2.</h1>
        <h5>Hier geht's los</h5>
        Suche im physischen und digitalen Bestand der ThULB.
        <img alt="tutorial step2" src="<?=$this->imageLink('Tut_BooksM.png')?>">
    </div>
    <div class="col-sm-4 col-xs-12 tutorial_sub">
        <h1>3.</h1>
        <h5>Du brauchst noch mehr?</h5>
        Suche in den von der ThULB lizenzierten Datenbanken.
        <img alt="tutorial step3" src="<?=$this->imageLink('TutArticleM.png')?>">
    </div>
  </div>
</div>