<table class="table table-striped">
  <? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
  <? $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls)
    || (isset($this->showBulkOptions) && $this->showBulkOptions); ?>
  <? $i = $this->indexStart; foreach ($this->results->getResults() as $current):
    $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
    <tr><td>
    <div id="result<?=$i++ ?>" class="result<?=$current->supportsAjaxStatus()?' ajaxItem':''?> <?=($i%2) ? 'even' : 'odd'?>">
      <div class="checkbox hidden-print">
        <?=$recordNumber ?>
      </div>
      <?=$this->record($current)->getSearchResult('list')?>
    </div>
    </td></tr>
  <? endforeach; ?>
</table>