<table class="table table-striped">
  <?php if (!isset($this->indexStart)) $this->indexStart = 0; ?>
  <?php $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls)
    || (isset($this->showBulkOptions) && $this->showBulkOptions); ?>
  <?php $i = $this->indexStart; foreach ($this->results->getResults() as $current):
    $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
    <tr><td>
    <div id="result<?= $i++ ?>" class="result<?= $current->supportsAjaxStatus()?' ajaxItem':''?>">
      <div class="record-number hidden-print">
        <?= $recordNumber ?>
      </div>
      <?= $this->record($current)->getSearchResult('list')?>
    </div>
    </td></tr>
  <?php endforeach; ?>
</table>