<?php if ($this->pageCount): ?>
  <ul class="pagination">
    <?php if (isset($this->previous)): ?>
      <?php if (!isset($this->options['disableFirst']) || !$this->options['disableFirst']): ?>
        <li><a href="<?= $this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>">[1]</a></li>
      <?php endif; ?>
      <li><a class="page-prev" title="<?= $this->transEsc('Prev')?>" href="<?= $this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><i class="fa fa-caret-left"></i></a></li>
    <?php endif; ?>

    <?php if (count($this->pagesInRange) > 1): ?>
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <li><a href="<?= $this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?= $page?></a></li>
        <?php else: ?>
          <li class="active"><span><?= $page?></span></li>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php if (isset($this->next)): ?>
      <li><a class="page-next" title="<?= $this->transEsc('Next');?>" href="<?= $this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><i class="fa fa-caret-right"></i></a></li>
      <?php if (!isset($this->options['disableLast']) || !$this->options['disableLast']): ?>
        <li><a href="<?= $this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>">[<?= $this->pageCount?>]</a></li>
      <?php endif; ?>
    <?php endif; ?>
  </ul>
<?php endif; ?>