<? $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, 'basic', $this->hiddenFilters); ?>
<? if (count($searchTabs) > 0): ?>
  <ul class="list-unstyled">
    <? foreach ($searchTabs as $tab): ?>
      <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
        <li<?=$tab['selected'] ? ' class="show"' : ''?>>
            <?=$this->transEsc($tab['label']); ?>
        </li>
      </a>
    <? endforeach; ?>
  </ul>
<? endif; ?>