<?php
  if(!$this->driver ?? null) {
    return;
  }
  if($this->driver instanceof \ThULB\RecordDriver\SolrVZGRecord && ($this->driver->isFormat('eBook') || $this->driver->isFormat('Book'))) {
    return;
  }

  $cleanDoi = $this->driver->getCleanDOI();
  $doi = $this->doi($this->driver, $this->location ?? '');
  $doiActive = $doi->isActive();
?>
<?php if ($doiActive && ($linkedDoi = $this->thulb_doiLinker($cleanDoi))): ?>
  <?php foreach($linkedDoi[$cleanDoi] as $linkedDoiData): ?>
    <a href="<?= $linkedDoiData['link'];?>" target="_blank" class="btn btn-primary unpaywall">
      <div><i class="fa fa-unlock-alt"></i></div>
      <?= $linkedDoiData['label'];?>
    </a>
  <?php endforeach; ?>
<?php endif; ?>
