<?php
  if($this->driver instanceof \ThULB\RecordDriver\SolrVZGRecord && $this->driver->isFormat('eBook')) {
    return;
  }
?>

<?= $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'doi.js', 'SET');?>

<div class="flex-center center-text">
  <img src="/themes/thulb/images/Ajax-loader.gif" class="doiLinkLoading">
  <span class="doiLink" data-doi="<?= $this->escapeHtml($doi)?>">
  </span>
</div>