<?php $summonResult = $this->recommend->getResults(); ?>
<?php if (!empty($summonResult['best_bets'])): ?>
<div class="authorbox">
  <?php foreach ($summonResult['best_bets'] as $current): ?>
    <p>
      <?php if (isset($current['link']) && !empty($current['link'])):?>
        <a href="<?= $this->escapeHtmlAttr($current['link'])?>"><?= $this->escapeHtml($current['title'])?></a>
      <?php else: ?>
        <b><?= $this->escapeHtml($current['title'])?></b>
      <?php endif; ?>
      <br/><?= $current['description']?>
    </p>
  <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if (!empty($summonResult['databases'])): ?>
<div class="authorbox">
  <p><?= $this->transEsc('summon_database_recommendations')?></p>
  <?php foreach ($summonResult['databases'] as $current): ?>
    <p><a href="<?= $this->escapeHtmlAttr($current['link'])?>"><?= $this->escapeHtml($current['title'])?></a><br/><?= $this->escapeHtml($current['description'])?></p>
  <?php endforeach; ?>
</div>
<?php endif; ?>
