<?
if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
} else {
    $user_id = false;
}
?>


<div class="row">
    <div class="col-sm-12">
        <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">

            <!-- Titel -->
            <tr>
                <th><?= $this->transEsc('Title') ?>:</th>
                <td>
                    <?= $this->thulb_metadatahelper()->title($this->driver) ?>
                </td>
            </tr>
        </table>
    </div>
</div>
