<div class="row hidden-xs hidden-sm">
  <div class="col-md-3">
    <ul>
      <h4>ThULB</h4>
      <li><a alt="Auskunft" title="Auskunft" href="http://www.thulb.uni-jena.de/KontaktAuskunft.html">Auskunft</a></li>
      <li><a href="http://www.thulb.uni-jena.de/kontakt_Teilbib.html">Öffnungszeiten</a></li>
      <li><a target="_blank" href="https://kataloge.thulb.uni-jena.de//loan/DB=1/SET=9/TTL=1/LNG=DU/USERINFO_LOGIN">Benutzerkonto</a></li>
      <li><a href="http://www.thulb.uni-jena.de/schulungen.html">Schulungen</a></li>		
      <li><a target="_blank" href="http://carrel.thulb.uni-jena.de/">CARREL</a></li>								
      <li><a href="http://www.thulb.uni-jena.de/impressum.html">Impressum</a></li>
    </ul>
  </div>
  <div class="col-md-3">
    <ul>
      <h4>Recherche</span></h4>								
      <li><a target="_blank" href="http://kataloge.thulb.uni-jena.de/DB=1/LNG=DU/">Online-Katalog</a></li>
      <li><a target="_blank" href="http://rzblx10.uni-regensburg.de/dbinfo/fachliste.php?bib_id=thulb">Datenbanken</a></li>
      <li><a target="_blank" href="http://rzblx1.uni-regensburg.de/ezeit/index.phtml?bibid=THULB&amp;colors=7&amp;lang=de">E-Zeitschriften</a></li>
      <li><a target="_blank" href="http://gso.gbv.de/DB=2.1/LNG=DU/">GVK</a></li>
      <li><a target="_blank" href="http://gso.gbv.de/DB=2.2/LNG=DU/">GVK-PLUS</a></li>
      <li><a target="_blank" href="http://www.ubka.uni-karlsruhe.de/kvk.html">KVK</a></li>
    </ul>
  </div>
  <div class="col-md-3">
    <ul>
      <h4>Thüringen</span></h4>
      <li><a target="_blank" href="http://www.urmel-dl.de">UrMEL</a></li>
      <li><a target="_blank" href="http://www.digitalesthueringen.de/">digitales thüringen</a></li>
      <li><a href="http://www.thulb.uni-jena.de/Handschriften__Sondersammlungen.html">Sammlungen</a></li>
      <li><a href="http://www.thulb.uni-jena.de/tb_html.html">Thüringen-Bibliographie</a></li>
      <li><a href="http://koha-info.thulb.uni-jena.de/">KOHA</a></li>
    </ul>							
  </div>
  <div class="cold-md-3">							
    <ul>
      <h4>Universität</span></h4>
      <li><a target="_blank" href="http://www.uni-jena.de/ssz.html">SSZ</a></li>
      <li><a target="_blank" href="https://friedolin.uni-jena.de/qisserver/rds?state=user&amp;type=0">Friedolin</a></li>
      <li><a target="_blank" href="http://www.uni-jena.de/URZ.html">URZ</a></li>
      <li><a target="_blank" href="http://www.uni-jena.de/thoska.html">Thoska</a></li>
      <li><a target="_blank" href="http://www.uni-jena.de/ASPA.html">ASPA</a></li>
    </ul>							
  </div>
</div>
