<nav class="navbar navbar-default hidden-xs">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><a href="http://www.thulb.uni-jena.de/Mailformulare/Discovery.html" target="_blank"><?= $this->transEsc("Header_contact")?></a></li>
      <li><a href="https://www.thulb.uni-jena.de/impressum.html" target="_blank"><?= $this->transEsc('Footer_imprint')?></a></li>
    </ul>
  </div>
</nav>
